db.VentasMobiles.insertMany([
    {Producto: "Iphone X" , MarcaProducto: "Apple" , PrecioUnitario: 395.70 ,  Venta: new Date("2020-01-01") , PrecioFabrica: 180,  Comprador: "Alberto G.", Vendedor:"Francisco"},
    {Producto: "Iphone XS" , MarcaProducto: "Apple" , PrecioUnitario: 466.00  ,  Venta: new Date("2020-01-01") , PrecioFabrica: 200,  Comprador: "Juan Alberto", Vendedor:"Francisco"},
    {Producto: "Iphone 11" , MarcaProducto: "Apple" , PrecioUnitario: 699.00 ,  Venta: new Date("2020-01-01") , PrecioFabrica: 250,  Comprador: "Maria Z.", Vendedor:"Francisco"},
    {Producto: "Iphone 8" , MarcaProducto: "Apple" , PrecioUnitario: 254.80 ,  Venta: new Date("2020-01-01") , PrecioFabrica: 150,  Comprador: "Manol", Vendedor:"Juanma"},
    {Producto: "P40" , MarcaProducto: "Huawei" , PrecioUnitario: 650.40 ,  Venta: new Date("2020-01-02") , PrecioFabrica: 300,  Comprador: "Maneli", Vendedor:"Juanma"},
    {Producto: "P40 Pro" , MarcaProducto: "Huawei" , PrecioUnitario: 740.50 ,  Venta: new Date("2020-01-02") , PrecioFabrica: 350,  Comprador: "Anna", Vendedor:"Jose"},
    {Producto: "P30" , MarcaProducto: "Huawei" , PrecioUnitario: 285.50 ,  Venta: new Date("2020-01-02") , PrecioFabrica: 250,  Comprador: "Anna", Vendedor:"Juanma"},
    {Producto: "P30 Pro" , MarcaProducto: "Huawei" , PrecioUnitario: 590.00 ,  Venta: new Date("2020-01-03") , PrecioFabrica: 280,  Comprador: "Anna", Vendedor:"Francisco"},
    {Producto: "P20 Lite" , MarcaProducto: "Huawei" , PrecioUnitario: 160.60 ,  Venta: new Date("2020-01-03") , PrecioFabrica: 100,  Comprador: "Juan Alberto", Vendedor:"Francisco"},
    {Producto: "Iphone 11 Pro" , MarcaProducto: "Apple" , PrecioUnitario: 722.00 ,Venta: new Date("2020-02-01") , PrecioFabrica: 270,  Comprador: "Karlos", Vendedor:"Francisco"},
    {Producto: "Iphone XR" , MarcaProducto: "Apple" , PrecioUnitario: 580.99 ,  Venta: new Date("2020-02-01") , PrecioFabrica: 230,  Comprador: "Juanma", Vendedor:"Jose"},
    {Producto: "Galaxy Note 20" , MarcaProducto: "Samsung" , PrecioUnitario: 660.55 ,  Venta: new Date("2020-02-01") , PrecioFabrica: 300,  Comprador: "Rafael", Vendedor:"Jose"},
    {Producto: "Galaxy S20" , MarcaProducto: "Samsung" , PrecioUnitario: 609.99 ,  Venta: new Date("2020-02-05") , PrecioFabrica: 280,  Comprador: "Juanma", Vendedor:"Juanma"},
    {Producto: "GalaxyZ Fold2" , MarcaProducto: "Samsung" , PrecioUnitario: 1599.99 ,  Venta: new Date("2020-02-05") , PrecioFabrica: 500,  Comprador: "Rafael", Vendedor:"Juanma"},
    {Producto: "Galaxy A51" , MarcaProducto: "Samsung" , PrecioUnitario: 239.99 ,  Venta: new Date("2020-02-06") , PrecioFabrica: 150,  Comprador: "Karlos", Vendedor:"Jose"},
    {Producto: "Iphone X" , MarcaProducto: "Apple" , PrecioUnitario: 395.70 ,  Venta: new Date("2020-02-06") , PrecioFabrica: 180,  Comprador: "Maria Z.", Vendedor:"Manuel"},
    {Producto: "Iphone X" , MarcaProducto: "Apple" , PrecioUnitario: 395.70 ,  Venta: new Date("2020-02-06") , PrecioFabrica: 180,  Comprador: "Pepito", Vendedor:"Francisco"},
    {Producto: "Iphone 8" , MarcaProducto: "Apple" , PrecioUnitario: 254.80 ,  Venta: new Date("2020-02-06") , PrecioFabrica: 150,  Comprador: "Joselito", Vendedor:"Manuel"},
    {Producto: "Iphone 8" , MarcaProducto: "Apple" , PrecioUnitario: 254.80  , Venta: new Date("2020-03-06") , PrecioFabrica: 150,  Comprador: "Karla", Vendedor:"Manuel"},
    {Producto: "P40" , MarcaProducto: "Huawei" , PrecioUnitario: 650.40  , Venta: new Date("2020-03-05") , PrecioFabrica: 300,  Comprador: "Karla", Vendedor:"Francisco"},
    {Producto: "Iphone X" , MarcaProducto: "Apple" , PrecioUnitario: 395.70, Venta: new Date("2020-04-05") , PrecioFabrica: 180,  Comprador: "Alberto G.", Vendedor:"Manuel"},
    {Producto: "Iphone X" , MarcaProducto: "Apple" , PrecioUnitario: 395.70 , Venta: new Date("2020-04-05") , PrecioFabrica: 180,  Comprador: "Hugo", Vendedor:"Manuel"},
    {Producto: "Galaxy S20" , MarcaProducto: "Samsung" , PrecioUnitario: 609.99 , Venta: new Date("2020-04-11") , PrecioFabrica: 280,  Comprador: "Maria Z.", Vendedor:"Francisco"},
    {Producto: "Galaxy Note 20" , MarcaProducto: "Samsung" , PrecioUnitario: 660.55  , Venta: new Date("2020-04-11") , PrecioFabrica: 300,  Comprador: "Alberto G.", Vendedor:"Francisco"},
    {Producto: "P40" , MarcaProducto: "Huawei" , PrecioUnitario: 650.40  , Venta: new Date("2020-04-11") , PrecioFabrica: 300,  Comprador: "Jesus", Vendedor:"Francisco"},
    {Producto: "P40" , MarcaProducto: "Huawei" , PrecioUnitario: 650.40  , Venta: new Date("2020-04-11") , PrecioFabrica: 300,  Comprador: "Alberto G.", Vendedor:"Jose"},

])